version: "3.9"
services:
  address-api:
    build: .
    image: komodo-address-api:dev
    container_name: komodo-address-api
    ports:
      - "7001:7001"       # local dev port mapping
    environment:
      PORT: "7010"
      GEOCODER: "mock"
    env_file: ./config/.env.dev