package handlers

import (
	"encoding/json"
	"net/http"

	logger "komodo-internal-lib-apis-go/logging/runtime"
)

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	UserID string `json:"user_id"`
}

func RegisterHandler(w http.ResponseWriter, r *http.Request) {
	var req RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request payload", http.StatusBadRequest)
		return
	}

	// Simulate user registration logic
	userID := "newly-generated-user-id" // This would be generated by your user service

	resp := RegisterResponse{
		UserID: userID,
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(resp); err != nil {
		logger.Error("failed to encode response: " + err.Error())
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
}