# Server configuration
server:
  port: 7002
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 30s

# Logging configuration
logging:
  level: warn
  format: text

# Database configuration
database:
  host: localhost
  port: 5432
  user: test_user
  password: test_password
  name: komodo_test
  sslmode: disable

# Geocoding service configuration
geocoding:
  provider: mock
  google_api_key: ""
  nominatim_base_url: ""

# External API configuration
external_apis:
  some_service:
    base_url: https://mock.someservice.com
    api_key: ""

# Feature flags
features:
  enable_some_feature: true
  enable_another_feature: true