openapi: 3.1.1
info:
  title: komodo-auth-api
  version: 0.1.0
servers:
  - url: http://localhost:7001
paths:
  # Health Check
  /health:
    get:
      summary: Health check
      tags: [Health, System]
      security:
        - BearerAuth: []
        - cookieAuth: []
      responses:
        200:
          description: OK,
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  # Login Operation
  /login:
    post:
      summary: User login endpoint
      tags: [Authentication]
      security:
        - BearerAuth: []
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Session or token cookie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized,
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden,
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    # Security
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        required: true
      cookieAuth:
        type: apiKey
        in: cookie
        name: session_token
    # Globals Responses
    DefaultResponse:
      type: object
      properties:
        status:
          enum: [success, failure]
    # Global Errors
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 404
        errorCode:
          type: string
          example: USER_NOT_FOUND
        message:
          type: string
          example: The requested resource was not found
      required:
        - statusCode
        - errorCode
        - message
    # Health
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          example: healthy
    # Login
    LoginRequest:
      description: Login request
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: P@ssw0rd
      required:
        - email
        - password
    LoginResponse:
      description: Login response
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
      required:
        - access_token
        - refresh_token
        - user_id
    # Logout
    LogoutRequest:
      description: Logout request
      type: object
      properties:
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      required:
        - refresh_token
    LogoutResponse:
      description: Logout response
      type: object
      properties:
        message:
          type: string
          example: Successfully logged out
    # MFA Disable
    MFADisableRequest:
      description: MFA Disable request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
      required:
        - user_id
    # MFA Enable
    MFAEnableRequest:
      description: MFA Enable request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
      required:
        - user_id
    # MFA Setup
    MFASetupRequest:
      description: MFA Setup request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
      required:
        - user_id
    # MFA Verify
    MFAVerifyRequest:
      description: MFA Verify request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
        code:
          type: string
          example: 123456
      required:
        - user_id
        - code
    # Password Change
    PasswordChangeRequest:
      description: Password Change request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
        old_password:
          type: string
          example: P@ssw0rd
        new_password:
          type: string
          example: N3wP@ssw0rd
      required:
        - user_id
        - old_password
        - new_password
    # Password Forgot
    PasswordForgotRequest:
      description: Password Forgot request
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
      required:
        - email
    PasswordForgotResponse:
      description: Password Forgot response
      type: object
      properties:
        status:
          enum: [email_sent, user_not_found]
          example: email_sent
    # Password Reset
    PasswordResetRequest:
      description: Password Reset request
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        new_password:
          type: string
          format: password
          example: N3wP@ssw0rd
      required:
        - email
        - new_password
    # Session Delete
    SessionDeleteRequest:
      description: Session Delete request
      type: object
      properties:
        session_token:
          type: string
          example: 2f1c8e7a-9b4d-4e2a-8c1f-7d2a3f4b5e6c
      required:
        - session_token
    # Session Create
    SessionCreateRequest:
      description: Session Create request
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
        device_info:
          type: string
          example: iPhone 12
      required:
        - user_id
    SessionCreateResponse:
      description: Session Create response
      type: object
      properties:
        session_token:
          type: string
          example: 2f1c8e7a-9b4d-4e2a-8c1f-7d2a3f4b5e6c
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
    # Signup
    SignupRequest:
      description: Signup request
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: N3wP@ssw0rd
      required:
        - email
        - password
    SignupResponse:
      description: Signup response
      type: object
      properties:
        user_id:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        session_token:
          type: string
          example: 2f1c8e7a-9b4d-4e2a-8c1f-7d2a3f4b5e6c
      required:
        - user_id
        - access_token
        - session_token
    # Token Refresh
    TokenRefreshRequest:
      description: Token Refresh request
      type: object
      properties:
        refresh_token:
          type: string
          example: b3e1a7c2-8f4b-4d2a-9e2f-7c1a2f3b4e5d
      required:
        - refresh_token
    TokenRefreshResponse:
      description: Token Refresh response
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      required:
        - access_token
        - refresh_token
    # Token Revoke
    TokenRevokeRequest:
      description: Token Revoke request
      type: object
      properties:
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      required:
        - refresh_token
    # Token Verify
    TokenVerifyRequest:
      description: Token Verify request
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      required:
        - access_token
    TokenVerifyResponse:
      description: Token Verify response
      type: object
      properties:
        valid:
          type: boolean
          example: true