# Server configuration
server:
  port: 8080
  read_timeout: 10s
  write_timeout: 15s
  idle_timeout: 60så

# Logging configuration
logging:
  level: debug
  format: json

# Feature flags
features:
  use_redis: true
  use_dynamo: true
  use_mfa: true
  use_oauth: true
  use_sms: true