package handlers

import (
	"encoding/json"
	errCodes "komodo-internal-lib-apis-go/http/common/errors"
	errors "komodo-internal-lib-apis-go/http/common/errors/chi"
	logger "komodo-internal-lib-apis-go/logging/runtime"
	"net/http"
)

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	UserID string `json:"user_id"`
}

func RegisterHandler(wtr http.ResponseWriter, req *http.Request) {
	var registerReq RegisterRequest
	if err := json.NewDecoder(req.Body).Decode(&registerReq); err != nil {
		logger.Error("failed to parse register request payload")
		errors.WriteErrorResponse(
			wtr,
			req,
			http.StatusInternalServerError,
			errCodes.ERR_INTERNAL_SERVER,
			"Failed to parse request payload",
		)
		return
	}

	// Simulate user registration logic
	userID := "newly-generated-user-id" // This would be generated by your user service

	resp := RegisterResponse{
		UserID: userID,
	}

	wtr.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(wtr).Encode(resp); err != nil {
		logger.Error("failed to encode response", err)
		errors.WriteErrorResponse(
			wtr,
			req,
			http.StatusInternalServerError,
			errCodes.ERR_INTERNAL_SERVER,
			"Failed to encode response",
		)
		return
	}
}